<resources>
    <string name="app_name">data</string>


    <string name="api_exception_unknown">Bilinmeyen bir sorun oluştu. Lütfen daha sonra tekrar deneyin.</string>
    <string name="api_exception_technical_error">Teknik aksaklıktan dolayı şuanda hizmet veremiyoruz, lütfen daha sonra
        tekrar deneyiniz.
    </string>
    <string name="network_error_msg">Bağlantı kaynaklı bir hata oluştu. Lütfen daha sonra tekrar deneyiniz</string>

</resources>
